name: Run Laravel Tests with Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
          extensions: mbstring, pdo_sqlite

      - name: Install dependencies
        run: |
          composer self-update && composer install && composer dump-autoload

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Configure SQLite in-memory DB
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          echo "DB_DATABASE=:memory:" >> .env

      - name: Run tests with coverage
        run: |
          ./vendor/bin/phpunit --coverage-clover=storage/coverage/clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
